# LAB 1 #
## Part A ##

First, we import the packages we need for the rest of the notebook.

In [18]:
import numpy as np

### Q1 ###
Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [19]:
q1 = np.arange(1, 20, 3)
print(q1)

[ 1  4  7 10 13 16 19]


### Q2 ### 
Create a new array of shape 3 with random numbers between 0 and 1.

In [20]:
q2 = np.random.rand(3,1)
print(q2.shape)
print(q2)

(3, 1)
[[0.75888599]
 [0.62192259]
 [0.13385123]]


### Q3 ###
Create a 2 D array `[[10,20,45], [30,12,16], [42,17,56]]` and perform the following operations: 
	 - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [95]:
q3 = np.array([[10,20,45], [30,12,16], [42,17,56]])

first_two_rows = q3[:2, :]
print(first_two_rows)

last_two_rows = q3[-2:, :]
print()
print(last_two_rows)

[[10 20 45]
 [30 12 16]]

[[30 12 16]
 [42 17 56]]


### Q4 ### 
Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [100]:
q4_1 = np.array([['a', 'b']])
q4_2 = np.array([['c', 'd']])

stack_vert = np.concatenate((q4_1, q4_2), axis= 0)
print(stack_vert)

stack_hori = np.concatenate((q4_1, q4_2), axis= 1)
print()
print(stack_hori)

# split arrays? How do you want me to splti it?

[['a' 'b']
 ['c' 'd']]

[['a' 'b' 'c' 'd']]


### Q5 ###
Create two matrices `X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),` 
	 - Is it possible to multiply these matrices? 
	 - Demonstrate the case when it is not possible to.

In [101]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y= np.array([[4, 2], [6, 2], [4, 2]])

print(X.shape)
print(Y.shape)

(3, 3)
(3, 2)


Since X is of shape (3,3) and Y is of shape(3,2), we can multiply the matrices as such:

In [102]:
np.matmul(X, Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

For the same reason, it is not possible to multiply the matrics in reverse order:

In [103]:
np.matmul(Y,X) # raises an error as it is an invalid matrix multiplication

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

### Q6 ###
Create two arrays, `x = ([2, -1, -8]) y = ([3, 1, -2]),`
	 - Find the Shape, Number of dimensions of vector x.
	 - Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [ ]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print(x.shape)
print(x.ndim)

x_reshaped = np.reshape(x, (3,1))
print(x_reshaped.ndim)

(3,)
1
2


### Q7 ###
How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [ ]:
q7 = np.full((3,3), 2)
print(q7)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


I can subtract elementwise from the matrix using broadcasting (of a scalar).

In [ ]:
q7_sub = q7 - 1
print(q7_sub)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


I can multiply through elementwise as well using broadcasting (which is different from matrix multiplication)

In [ ]:
mult_val = np.array([1,2,3]) # creating a sample 1x3 array
q7_matmul = np.matmul(q7, mult_val) # doing matmul on the sample
q7_broadcast_mul = q7 * mult_val # doing broadcasting on the sample

# We check to see that the values are different
print(q7_matmul)
print(q7_broadcast_mul)

[12 12 12]
[[2 4 6]
 [2 4 6]
 [2 4 6]]


## Part B ##

### B.1 ###

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [108]:
# converting the system of linear equation to matrix
bX_1 = np.array([[4,1,-2], [2,-3,2], [1,2,3]])
bY_1 = np.array([10,-4,6]).reshape(3,1)

# Check the determinant of the left matrix
detX_1 = np.linalg.det(bX_1)
print(detX_1)

-70.00000000000003


Since the determinant of the matrix is non-zero, it is non-singular and thus the system of linear equation it represents can be solved.

In [110]:
sol_1 = np.linalg.solve(bX_1, bY_1)
print(sol_1)

[[ 1.8]
 [ 2.4]
 [-0.2]]


The solution to the system of linear equation is $x=1.8, y=2.4, z=-0.2$

### B.2 ###

1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [119]:
# Similar to above, we first convert the system to a matrix
bX_2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], \
                 [3, 1, -2, 2], [1, 3, -4, 1]])
bY_2 = np.array([10,20, 3, -1]).reshape(1, 4)

# Check the determinant of the left matrix
detX_2 = np.linalg.det(bX_2)
print(detX_2)

0.0


Since the determinant of the matrix representing the system of linear equation is equal to 0, this system is singular, and thus a unique solution cannot be defined.

We can also see that equation 2 in the system is a linear combination of equation 1 (we simply multiply 2 through the equation). This further shows that the system is singular, and thus no unique solution can be found.